steps:
  # Create lowercase branch name for GCP labels
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "${BRANCH_NAME,,}" > /workspace/branch_lower.txt
        cat /workspace/branch_lower.txt

  # Debug step: Show the values that will be used
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Staging Backend Build Debug ==="
        echo "BRANCH_NAME: ${BRANCH_NAME}"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "Environment: STAGING"
        echo "=== End Debug ==="

  # Build the Docker image for staging
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/lad-backend-stage:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/lad-backend-stage:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/lad-backend-stage:$BRANCH_NAME',
      '-t', 'gcr.io/$PROJECT_ID/lad-backend-stage:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/lad-backend-stage:latest',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '--build-arg', 'NODE_ENV=staging',
      '.'
    ]

  # Push the Docker images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lad-backend-stage:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lad-backend-stage:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lad-backend-stage:$BRANCH_NAME']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lad-backend-stage:latest']

  # Deploy to Cloud Run (Staging Backend)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        BRANCH_LOWER=$(cat /workspace/branch_lower.txt)
        
        echo "========================================"
        echo "Starting Cloud Run Staging Deployment"
        echo "Service: $_SERVICE_NAME"
        echo "Region: $_REGION"
        echo "Image: gcr.io/$PROJECT_ID/lad-backend-stage:$COMMIT_SHA"
        echo "Environment: STAGING"
        echo "========================================"
        
        # Deploy to Cloud Run
        gcloud run deploy $_SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/lad-backend-stage:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 2 \
          --min-instances 0 \
          --max-instances 5 \
          --concurrency 80 \
          --timeout 300 \
          --set-secrets JWT_SECRET=jwt-secret:latest,OPENAI_API_KEY=openai-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,APOLLO_API_KEY=apollo-api-key:latest,UNIPILE_API_KEY=unipile-api-key:latest,UNIPILE_DSN=UNIPILE_DSN:latest,UNIPILE_TOKEN=UNIPILE_TOKEN:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest \
          --remove-env-vars PORT \
          --update-env-vars NODE_ENV=staging,ENVIRONMENT=staging,JWT_EXPIRES_IN=7d,BRANCH=$BRANCH_NAME,COMMIT_SHA=$SHORT_SHA,BUILD_ID=$BUILD_ID,POSTGRES_HOST=165.22.221.77,POSTGRES_PORT=5432,POSTGRES_USER=dbadmin,POSTGRES_PASSWORD=TechieMaya,POSTGRES_DB=salesmaya_agent,POSTGRES_SCHEMA=lad_stage,POSTGRES_MAX_CLIENTS=10,POSTGRES_IDLE_TIMEOUT=30000,FRONTEND_URL=$_FRONTEND_URL,BACKEND_URL=$_BACKEND_URL,BASE_URL=https://voag.techiemaya.com,BASE_URL_FRONTEND_HEADER=$_FRONTEND_HEADER,BASE_URL_FRONTEND_APIKEY=$_FRONTEND_APIKEY,DEFAULT_TENANT_ID=00000000-0000-0000-0000-000000000001,GCP_PROJECT_ID=$_GCP_PROJECT_ID,GCP_LOCATION=$_GCP_LOCATION,FOLLOWUP_QUEUE_NAME=$_FOLLOWUP_QUEUE_NAME,FOLLOWUP_EXECUTION_ENDPOINT=$_FOLLOWUP_EXECUTION_ENDPOINT,DEFAULT_FOLLOW_UP_AGENT_ID=$_DEFAULT_FOLLOW_UP_AGENT_ID,APOLLO_WEBHOOK_URL=$_APOLLO_WEBHOOK_URL,GOOGLE_CLOUD_PROJECT=$_GCP_PROJECT_ID,CLOUD_TASKS_LOCATION=$_GCP_LOCATION,CLOUD_TASKS_QUEUE_NAME=$_CLOUD_TASKS_QUEUE_NAME,CLOUD_RUN_SERVICE_URL=$_BACKEND_URL \
          --update-labels environment=staging,branch=$${BRANCH_LOWER},commit-sha=$SHORT_SHA,managed-by=cloud-build
        
        DEPLOY_STATUS=$$?
        echo "========================================"
        if [ $$DEPLOY_STATUS -eq 0 ]; then
          echo "✓ Staging deployment completed successfully!"
          echo "✓ Service URL: https://$_SERVICE_NAME-741719885039.$_REGION.run.app"
        else
          echo "✗ Deployment failed with status: $$DEPLOY_STATUS"
          exit $$DEPLOY_STATUS
        fi
        echo "========================================"

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/lad-backend-stage:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/lad-backend-stage:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/lad-backend-stage:$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/lad-backend-stage:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# Timeout for the entire build
timeout: '1200s'

# Substitutions for Staging Environment
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'lad-backend-stage'
  _ENV: 'staging'
  _FRONTEND_URL: 'https://lad-frontend-stage-741719885039.us-central1.run.app'
  _BACKEND_URL: 'https://lad-backend-stage-741719885039.us-central1.run.app'
  _CORS_ORIGINS: 'https://lad-frontend-stage-741719885039.us-central1.run.app,https://lad-frontend-stage-3nddlneyya-uc.a.run.app,https://stage.mrlads.com'
  _FRONTEND_HEADER: 'settings'
  _FRONTEND_APIKEY: '_L5cf6UXDkGTcWRaHka9Q13Kmu4k5dxaKEPRH165U8U'
  _GCP_PROJECT_ID: 'salesmaya-pluto'
  _GCP_LOCATION: 'us-central1'
  _FOLLOWUP_QUEUE_NAME: 'follow-up-voag-calls-v2-stage'
  _FOLLOWUP_EXECUTION_ENDPOINT: 'https://lad-backend-stage-741719885039.us-central1.run.app/api/deal-pipeline/bookings'
  _DEFAULT_FOLLOW_UP_AGENT_ID: '24'
  _APOLLO_WEBHOOK_URL: 'https://apollo-phone-service-741719885039.us-central1.run.app/api/webhook/apollo-phone'
  _CLOUD_TASKS_QUEUE_NAME: 'campaign-scheduler-task'
